"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[package]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "

[lua]
symbol = " "

[git_branch]
symbol = " "
format = "[$symbol$branch(:$remote_branch)]($style) "

[cmake]
symbol = "卑 "

[golang]
symbol = "ﳑ "

[rust]
symbol = " "
